// Auto-generated by scripts/gen_build_version.py - DO NOT EDIT MANUALLY
`ifndef BUILD_VERSION_VH
`define BUILD_VERSION_VH

`define GIT_COMMIT_HASH 32'h7c9e93d2
`define GIT_DIRTY       1'b1
`define BUILD_DATE      32'h20261008
`define TARGET_MHZ      8'd200
`define PLL_MULT        4'd14

`endif // BUILD_VERSION_VH
