#!/usr/bin/env python3
"""
Generate build_version.vh containing Git commit hash, dirty flag, and build date.
Invoked automatically before FPGA synthesis and simulation builds.
"""

import subprocess
import datetime
import os
import sys

def get_git_info():
    # 1. Commit hash (8 hex characters = 32 bits)
    try:
        hash_out = subprocess.check_output(
            ["git", "rev-parse", "--short=8", "HEAD"],
            stderr=subprocess.DEVNULL
        ).decode().strip()
        # Ensure it's exactly 8 hex digits
        if len(hash_out) < 8:
            hash_out = hash_out.ljust(8, '0')
        elif len(hash_out) > 8:
            hash_out = hash_out[:8]
    except Exception:
        hash_out = "00000000"

    # 2. Dirty working tree flag
    try:
        status = subprocess.check_output(
            ["git", "status", "--porcelain"],
            stderr=subprocess.DEVNULL
        ).decode().strip()
        is_dirty = "1'b1" if len(status) > 0 else "1'b0"
    except Exception:
        is_dirty = "1'b0"

    # 3. Build date (YYYYMMDD in BCD format)
    now = datetime.datetime.now()
    date_str = now.strftime("%Y%m%d")

    return hash_out, is_dirty, date_str

def main():
    repo_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    target_vh = os.path.join(repo_dir, "build_version.vh")

    hash_val, is_dirty, date_val = get_git_info()

    content = f"""// Auto-generated by scripts/gen_build_version.py - DO NOT EDIT MANUALLY
`ifndef BUILD_VERSION_VH
`define BUILD_VERSION_VH

`define GIT_COMMIT_HASH 32'h{hash_val}
`define GIT_DIRTY       {is_dirty}
`define BUILD_DATE      32'h{date_val}
`define TARGET_MHZ      8'd200
`define PLL_MULT        4'd14

`endif // BUILD_VERSION_VH
"""

    if os.path.exists(target_vh):
        try:
            with open(target_vh, "r") as f:
                if f.read() == content:
                    print(f"[gen_build_version] {target_vh} is up to date (hash: {hash_val}, date: {date_val})")
                    return
        except Exception:
            pass

    with open(target_vh, "w") as f:
        f.write(content)

    print(f"[gen_build_version] Generated {target_vh} (commit: {hash_val}, dirty: {is_dirty}, date: {date_val})")

if __name__ == "__main__":
    main()
